apiVersion: v1
kind: Secret
metadata:
  name: mongodb-crud-secret
  namespace: david-eini12-dev
type: Opaque
stringData:
  MONGODB_HOST: mongodb
  MONGODB_DATABASE: enemy_soldiers
  MONGODB_USER: david
  MONGODB_PASSWORD: pass
