apiVersion: v1
kind: Service
metadata:
  name: python-app-crud-mongo
  namespace: david-eini12-dev
spec:
  selector:
    app: python-app-crud-mongo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP