apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: david-eini12-dev
  name: mongodb-deployment
  annotations: {}
spec:
  selector:
    matchLabels:
      app: mongodb-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-deployment
    spec:
      containers:
        - name: mongodb-deployment
          image: mongodb:latest
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
          - name: MONGODB_HOST
            valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_HOST
          - name: MONGODB_DATABASE
            valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_DATABASE
          - name: MONGODB_USER
            valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_USER
          - name: MONGODB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_PASSWORD
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
