apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: david-eini12-dev
  name: mongodb-deployment
  annotations: {}
spec:
  selector:
    matchLabels:
      app: mongodb-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-deployment
    spec:
      containers:
        - name: mongodb-deployment
          image: mongodb:latest
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
          - name: MONGO_DATABASE
            valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_DATABASE
          - name: MONGO_USER
            valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_USER
          - name: MONGO_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASSWORD
          volumeMounts:
            - name: mongo-storage
              mountPath: /var/lib/mongo_data
      imagePullSecrets: []
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
