apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: david-eini12-dev
spec:
  selector:
    app: mongodb-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017