apiVersion: v1
kind: Secret
metadata:
  name: mongo-crud-secret
  namespace: david-eini12-dev
type: Opaque
stringData:
  MONGO_PORT: '27017'
  MONGO_HOST: "mongo"
  MONGO_DATABASE: "enemy_soldiers"
  MONGO_USER: "root"
  MONGO_PASSWORD: "pass"
